### PR TITLE
Refactor code into python package

### PR DESCRIPTION
**Pull request by yycho0108**
This PR migrates all existing code into a python package `top` that roughly looks like the following:
```bash
top
├── data
│   ├── augment.py
│   ├── __init__.py
│   ├── objectron_dataset.py
├── __init__.py
├── model
│   ├── backbone.py
│   ├── __init__.py
│   └── layers.py
└── run
    ├── __init__.py
    ├── path_util.py
    └── train_util.py
```
So it's quite a straightforward organization. This directly is in turn a sub-directory of `src` and at the top level we have the `pyproject.toml` for package specification (as opposed to `setup.py`). This choice might entail that we have to use a tool like `poetry` for easier editable-mode installations (`pip install -e .` does not support `pyproject.toml`). @ajy8456 Let me know if you have any questions. The current intent is to simultaneously support `python==3.6.9` (my desktop, `ubuntu 18.04`) and `python>=3.7` (jiyong's settings which I think is at `python3.8` with `ubuntu 20.04`)

### CODE REVIEW

**Comment by ajy8456** [comment]
That file structure looks good.
I don't exactly understand about '.toml'. Do you means that using '.toml' & poetry is needed for satisfied our setting both? My setting is python==3.7.10 & ubuntu 18.04.

**Comment by yycho0108** [comment]
@ajy8456 If we want to be very careful about package version consistency, then yes. Then again, I'm just experimenting with `poetry` to see how well it would work for package maintenance purposes. We could always revert to the old style with some permutation of [`setup.py`, `setup.cfg`, `requirements.txt`] if we feel like this is more of a burden.

**Comment by ajy8456** [comment]
> @ajy8456 If we want to be very careful about package version consistency, then yes. Then again, I'm just experimenting with `poetry` to see how well it would work for package maintenance purposes. We could always revert to the old style with some permutation of [`setup.py`, `setup.cfg`, `requirements.txt`] if we feel like this is more of a burden.

I got it! Let's try with poetry.

**Comment by yycho0108** [comment]
@ajy8456 If you'd like to test this branch then you would need to do some combination of the following:

```
# install poetry from current master
pushd /tmp
wget https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py
python install-poetry.py --git https://github.com/python-poetry/poetry.git@master
rm install-poetry.py
popd

git checkout repackage
poetry install
# poetry shell # run this command to enter virtualenv which would give you a shell to test whether the installation is working
```

Take the above set of commands as a reference rather than a strict guide, since I'm not 100% sure if it would just work out of the box.

**Comment by yycho0108** [comment]
Anyway, it's probably useful to cite the usual software mindset of `Ask forgiveness, not permission` -- i.e. the rationale here is "in the absence of an agreed-upon arbitration on how best to maintain a package, let's try `poetry` which seems like a potentially useful option and then revert to other styles if the plan falls through." Hopefully you're on board with this.

**Review by ajy8456 — APPROVED** [review]
LGTM

**Comment by ajy8456** [comment]
> @ajy8456 If you'd like to test this branch then you would need to do some combination of the following:
> 
> ```shell
> # install poetry from current master
> pushd /tmp
> wget https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py
> python install-poetry.py --git https://github.com/python-poetry/poetry.git@master
> rm install-poetry.py
> popd
> 
> git checkout repackage
> poetry install
> # poetry shell # run this command to enter virtualenv which would give you a shell to test whether the installation is working
> ```
> 
> Take the above set of commands as a reference rather than a strict guide, since I'm not 100% sure if it would just work out of the box.



> @ajy8456 If you'd like to test this branch then you would need to do some combination of the following:
> 
> ```shell
> # install poetry from current master
> pushd /tmp
> wget https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py
> python install-poetry.py --git https://github.com/python-poetry/poetry.git@master
> rm install-poetry.py
> popd
> 
> git checkout repackage
> poetry install
> # poetry shell # run this command to enter virtualenv which would give you a shell to test whether the installation is working
> ```
> 
> Take the above set of commands as a reference rather than a strict guide, since I'm not 100% sure if it would just work out of the box.

I am following those lines, but It can't find command 'poetry'. Is "pushd~popd" doing install poetry, isn't it?

**Pull request merged**
